config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "sessions#new"
  
  resource :session
  resources :users
  resources :books
  resources :reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews

  validates :title, presence: true
  validates :author, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 7 }

  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_authenticated_user

  def require_authenticated_user
    redirect_to new_session_path unless current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show]

  # GET /books
  def index
    @books = Book.all
  end

  # GET /books/1
  def show
    @reviews = @book.reviews
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # POST /books
  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book, notice: "Book was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :author, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all.limit(20)
  end

  def new
    @books = Book.all.limit(20)
    @review = Review.new
  end

  def create
    @review = Review.new(book_id: params[:review][:book_id].to_i, rating: params[:review][:rating].to_i, content: params[:review][:content], title: params[:review][:title])
    @review.user = current_user

    if @review.save
      redirect_to reviews_path
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :require_authenticated_user, except: :destroy

  def new
    if current_user.present?
      redirect_to reviews_path
    end
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to reviews_path
    else
      flash[:alert] = "Email or password is invalid"
      redirect_to new_session_path
    end
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil

    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<%# locals: (book:) %>
<div id="<%= dom_id book %>">
  <p class="text-xl font-bold">
    <%= book.title %>
  </p>

  <p class="my-2">
    <strong class="inline-block font-medium mb-1">Written by:</strong> <%= book.author %>
  </p>

  <p class="my-2">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= book.description %>
  </p>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book, class: "contents") do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label "Title of the book" %>
    <%= form.text_field :title %>
  </div>

  <div class="my-5">
    <%= form.label "Author" %>
    <%= form.text_field :author %>
  </div>

  <div class="my-5 h-32">
    <%= form.label "Blurb for the book" %>
    <%= form.text_area :blurb %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-green-700 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/books/index.html.erb
<div class="w-full">
  <% content_for :title, "Books" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Books</h1>
    <%= link_to "New book", new_book_path, class: "rounded-lg py-3 px-5 bg-green-700 text-white block font-medium" %>
  </div>

  <div id="books" class="min-w-full space-y-4 mt-4">
    <% @books.each do |book| %>
      <div class="card">
        <%= render book %>
        <%= link_to "Read reviews", book, class: "rounded-lg py-3 px-5 bg-green-200 inline-block font-medium" %>
        <%= link_to "Add your review", new_review_path, class: "rounded-lg py-3 px-5 bg-green-200 inline-block font-medium" %>
      </div>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New book</h1>

  <%= render "form", book: @book %>

  <%= link_to "Back to books", books_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-200 inline-block font-medium" %>
</div>

app/views/books/show.html.erb
<div class="mx-auto w-full flex">


  <div class="space-y-4">
    <div class="card">
      <%= render @book %>
      <%= link_to "Back", books_path, class: "rounded-lg py-3 px-5 bg-gray-200 inline-block font-medium" %>
    </div>

    <% unless @reviews.length.positive? %>
      <div class="card flex justify-center">
        <div>
          <p class="text-center mt-4">No reviews yet</p>
          <%= link_to "Add a review", new_review_path, class: "rounded-lg block py-3 px-5 mt-2 bg-green-700 text-white inline-block font-medium cursor-pointer" %>
        </div>
      </div>
    <% end %>

    <div class="grid grid-cols-3 gap-4">
      <% @reviews.each do |review| %>
        <div class="card">
          <h2 class="text-xl font-bold"><%= review.title %></h2>
          <p class="text-sm text-gray-500">Rating: <%= review.rating %></p>
          <p class="text-sm text-gray-500">By <%= review.user.name %></p>
          <p class="mt-4"><%= review.content %></p>
        </div>
      <% end %>
      <div class="card">
        <p class="text-center mt-4 text-md">Read this book?</p>
        <%= link_to "Add your review", new_review_path, class: "rounded-lg block mx-auto py-3 px-5 mt-2 bg-green-700 text-white text-center block font-medium cursor-pointer" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BetterReads</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if alert.present? %>
      <div class="bg-red-200 border-red-300 border text-red-500 font-bold text-center p-2 rounded w-1/3 m-auto relative">
        <%= alert %>
      </div>
    <% end %>
    <% if notice.present? %>
      <div class="bg-green-200 border-green-300 border text-green-500 font-bold text-center p-2 rounded w-1/3 m-auto relative">
        <%= notice %>
      </div>
    <% end %>
    <% if current_user.present? %>
      <nav class="bg-gray-800 text-white p-4">
        <div class="container mx-auto flex justify-between">
          <a href="<%= root_path %>" class="font-bold">BetterReads</a>
            <div class="flex space-x-4">
              <%= link_to "Books", books_path %>
              <%= link_to "Reviews", reviews_path %>
              <%= link_to "Logout", session_path,  data: {turbo_method: :delete} %>
            </div>
          </div>
        </div>
      </nav>
    <% end %>
    <main class="container mx-auto mt-8 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/reviews/_form.html.erb
<%# locals: (review:) %>
<%= form_with(model: review, class: "contents") do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label "Select the book you are reviewing" %>
    <%= form.collection_select :book_id, Book.all, :id, :title %>
  </div>

  <div class="my-5">
    <%= form.label "Title" %>
    <%= form.text_field :title, required: true %>
  </div>

  <div class="my-5">
    <%= form.label :star_rating %>
    <%= form.select :rating, [1, 2, 3, 4, 5] %>
  </div>

  <div class="my-5">
    <%= form.label :your_review %>
    <%= form.text_area :content, class: "w-full h-32" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-green-700 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/reviews/index.html.erb
<div class="flex flex-col space-y-4">
  <h1 class="text-3xl font-bold">Recent reviews</h1>
  <div class="grid grid-cols-2 gap-4">
    <%# TODO: could make this a partial? %>
    <% @reviews.map do |review| %>
      <div class="card">
        <h2 class="text-xl font-bold"><%= review.title %></h2>
        <p class="text-md text-black mb-2">Review for "<%= review.book.title %>"</p>
        <p class="text-sm text-gray-500">Rating: <%= review.rating %></p>
        <p class="text-sm text-gray-500">By <%= review.user.name %></p>
        <p class="mt-4"><%= review.content %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Write a review</h1>

  <%= render "form", review: @review %>

  <%= link_to "Back", url_for(:back), class: "ml-2 rounded-lg py-3 px-5 bg-gray-200 inline-block font-medium" %>
</div>

app/views/users/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#show</h1>
  <p>Find me in app/views/users/show.html.erb</p>
</div>